apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slo-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "slo-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "slo-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "slo-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "slo-operator.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- range .Values.watchNamespaces }}
            - --namespace={{ . }}
            {{- end }}
          env:
            - name: SLO_PROMETHEUS_URL
              value: {{ .Values.prometheus.url | quote }}
            - name: SLO_BUDGET_INTERVAL_SECONDS
              value: {{ .Values.prometheus.budgetIntervalSeconds | quote }}
            {{- if .Values.prometheusRuleLabels }}
            - name: SLO_PROMETHEUSRULE_LABELS
              value: {{ range $i, $k := (keys .Values.prometheusRuleLabels | sortAlpha) }}{{ if $i }},{{ end }}{{ $k }}={{ index $.Values.prometheusRuleLabels $k }}{{ end }}
            {{- end }}
          ports:
            - name: healthz
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
